spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mobile_ms
      username: root
      password: Garud@13
      
  jpa:
    generate-ddl: true
    show-sql: true
    
mobilestore:
  vendor-name: AMAZON
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/    
