spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mobile_store
      username: root
      password: Garud@13
      
  jpa:
    generate-ddl: true
    show-sql: true
    
mobilestore:
  vendor-name: AMAZON
  
